M <- c("adaptMCMC", "adaptsmoFMRI", "addhaz", "ADDT", "ADMMnet", "agop", "ahaz", 
       "AMIAS", "APML0", "arm", "arules", "arulesCBA", "aster2", "BacArena", 
       "BayesFactor", "bayesGDS", "bc3net", "BCE", "bdots", "bgsmtr", "biglasso", 
       "BinNonNor", "BinNor", "bnstruct", "BTLLasso", "BullsEyeR", "cAIC4", "CAM", 
       "centiserve", "cgam", "cjoint", "climwin", "CLSOCP", "corpustools", "covLCA", 
       "CoxBoost", "cpgen", "cplm", "crqa", "crrp", "CRTgeeDR", "cthreshER", 
       "ctmcmove", "CVST", "cvxbiclustr", "cvxclustr", "Data2LD", "dataPreparation", 
       "dcGOR", "dclone", "dglars", "dhglm", "distrom", "dmm", "DODR", "DoubleCone", 
       "DRR", "DWDLargeR", "EMCluster", "EMMREML", "epistasis", "epoc", "excursions", 
       "expm", "fanc", "fastclime", "fda", "fExpressCertificates", "FIAR", "flare", 
       "frailtyHL", "FRegSigCom", "FSTpackage", "FTICRMS", "GAMBoost", "gamlr", 
       "gamm4", "gcdnet", "gdistance", "GeDS", "geeM", "GenOrd", "GeoDE", "geostatsp", 
       "GHap", "glmm", "glmnet", "gptk", "GPvam", "GrassmannOptim", "gremlin", 
       "growthrate", "grpregOverlap", "gskat", "gvcm.cat", "gwerAM", "hdlm", "hglm", 
       "hglm.data", "HiCfeat", "HSDiC", "huge", "ibmdbR", "IGG", "inarmix", "inca", 
       "IPMpack", "irlba", "irregulAR1", "isotonic.pen", "kerasformula", "kinship2", 
       "klin", "lassoscore", "ldr", "lfe", "lme4", "logcondiscr", "LPmerge", "LSC", 
       "mapfit", "MargCond", "Matrix.utils", "MBC", "MBSP", "mcen", "mclogit", 
       "MCMCglmm", "mdhglm", "MDPtoolbox", "mediation", "MEET", "mefa4", "metafor", 
       "Metatron", "mgwrsar", "mht", "mi", "minque", "MMS", "mosaic", "msda", "msgl", 
       "multiAssetOptions", "MultiGHQuad", "MultiOrd", "MultiVarSel", "mvglmmRank", 
       "nadiv", "NegBinBetaBinreg", "netcoh", "netgsa", "networkR", 
       "NetworkRiskMeasures", "optbdmaeAT", "optimbase", "optrcdmaeAT", 
       "ORDER2PARENT", "orderedLasso", "OrdNor", "PCovR", "pedgene", "pedigree", 
       "pedigreemm", "penDvine", "pense", "phateR", "PhylogeneticEM", "picasso", 
       "PivotalR", "pleio", "PoisBinNonNor", "PoisBinOrd", "PoisBinOrdNonNor", 
       "PoisBinOrdNor", "PoisNonNor", "PoisNor", "PrevMap", "PRISMA", "ProbitSpatial", 
       "prodest", "qgtools", "qlcMatrix", "qpcR", "QRM", "quadrupen", "qut", "QZ", 
       "ramps", "randnet", "rCUR", "RealVAMS", "REBayes", "recommenderlab", 
       "reglogit", "REREFACT", "RFGLS", "RGENERATEPREC", "Rmagic", "Rmosek", 
       "RMRAINGEN", "RNewsflow", "robustlmm", "RSarules", "rsggm", "rwc", "SALES", 
       "scpm", "sdpt3r", "sdwd", "sensory", "serrsBayes", "Seurat", "sglasso", 
       "sglOptim", "SmallCountRounding", "snpReady", "softImpute", "sommer", 
       "soptdmaeA", "SOR", "spacejam", "sparsestep", "spatialprobit", 
       "SpatioTemporal", "spdep", "speedglm", "sRDA", "SSBtools", 
       "sSDR", "ssfa", "StableEstim", "SubgrpID", "SuperPCA", "survey", "svcm", 
       "svmplus", "sybil", "sybilccFBA", "sybilcycleFreeFlux", "systemfit", 
       "textir", "textmineR", "textTinyR", "TimeProjection", "tmvtnorm", "TPEA", 
       "TreePar", "triversity", "tvReg", "ViSiElse", "winRatioAnalysis", "wordspace", 
       "abnormality", "AdaptiveSparsity", "adjclust", "ADMM", "AGHmatrix", 
       "AICcmodavg", "apcluster", "apdesign", "arc", "ArCo", "aricode", "AROC", 
       "ashr", "asnipe", "automultinomial", "bamlss", "basefun", "bastah", 
       "BayesianTools", "BayesS5", "bayou", "BDgraph", "beam", "benchmarkme", 
       "Bergm", "BeSS", "bibliometrix", "BigQuic", "BinOrdNonNor", "blin", 
       "BlockCov", "blockmodeling", "blockseg", "BMhyb", "bootnet", 
       "BradleyTerryScalable", "brainGraph", "brant", "BreedingSchemeLanguage", 
       "brglm2", "bridgesampling", "brms", "btergm", "BTYD", "cape", "catch", 
       "CatEncoders", "CEGO", "ChainLadder", "cherry", "chinese.misc", "chords", 
       "CIAAWconsensus", "CISE", "cleanNLP", "cliqueMS", "CluMix", "clustvarsel", 
       "CNull", "CNVScope", "coalescentMCMC", "codingMatrices", "CollocInfer", 
       "colourvision", "comato", "CompareCausalNetworks", "complexplus", "control", 
       "cooccurNet", "cope", "copula", "Corbi", "CorReg", "CorShrink", "Countr", 
       "CovTools", "coxinterval", "coxme", "CRF", "crisp", "Crossover", "ctsem", 
       "CVXR", "Cyclops", "DAISIE", "DCD", "DDD", "demu", "denoiseR", "denseFLMM", 
       "detect", "DiffNet", "diffusionMap", "dmt", "dnet", "DNMF", "DOBAD", "doBy", 
       "dplR", "dr4pl", "DRaWR", "DrBats", "dtwclust", "DWLasso", "dynr", "econet", 
       "ECOSolveR", "EdSurvey", "EFDR", "effectFusion", "egoTERGM", "eNetXplorer", 
       "ePCR", "Epi", "episode", "ergm", "eRm", "eva", "evclust", "evolqg", 
       "expoRkit", "ez", "face", "facilitation", "fastcox", "FastImputation", 
       "fastLink", "fbar", "fdapace", "FDboost", "FeatureHashing", "fGarch", 
       "FindIt", "flars", "FlexGAM", "ForecastComb", "fpmoutliers", "frailtyEM", 
       "FREGAT", "FRK", "FSInteract", "FTRLProximal", "funcy", "fuser", 
       "gamm4.test", "gcbd", "geecure", "geex", "GENLIB", "GeomComb", "geomorph", 
       "GFD", "gllvm", "glmmLasso", "glmmsr", "glmmTMB", "glmnetUtils", "gMCP", 
       "gnm", "goric", "graphicalVAR", "gRbase", "grf", "grpreg", "gustave", 
       "GWSDAT", "hbm", "hbsae", "HDCI", "HDPenReg", "HiCblock", "HiCglmi", 
       "hierarchicalDS", "hierarchicalSets", "highriskzone", "higrad", "HLMdiag", 
       "hmi", "HRQoL", "hts", "icdGLM", "IDE", "igraph", "iilasso", "influence.ME", 
       "influenceR", "INLABMA", "inlabru", "intercure", "IPCAPS", "iRF", "IsingFit", 
       "iTOP", "ITRSelect", "ivmodel", "joineRmeta", "joineRML", "JWileymisc", 
       "kknn", "KMgene", "knockoff", "ks", "L0Learn", "LANDD", "landsepi", 
       "LassoBacktracking", "lavaSearch2", "lgcp", "LICORS", "lilikoi", "lime", 
       "lineqGPR", "LMERConvenienceFunctions", "lmeresampler", "lmvar", "loggle", 
       "lognorm", "lolog", "lpbrim", "LPR", "lsbs", "ltmle", "ludic", "lvnet", 
       "madness", "MANOVA.RM", "marcher", "marked", "markovchain", "mase", 
       "MatrixModels", "mboost", "mcglm", "MCMCprecision", "mcompanion", "medflex", 
       "MEGENA", "MendelianRandomization", "merDeriv", "MESS", "metaBLUE", "metaboGSE", 
       "metafuse", "metagear", "MetamapsDB", "metaMix", "metaSEM", "MFKnockoffs", "MFPCA", 
       "mgcv", "micemd", "midasr", "MIIVsem", "miRNAss", "misclassGLM", "mistral", 
       "MixedPsy", "MixfMRI", "mixKernel", "mlapi", "MlBayesOpt", "MLGL", "mlmm.gwas", 
       "mltools", "MM4LMM", "mmmgee", "Morpho", "moult", "mRchmadness", "MRFcov", 
       "msaenet", "MuChPoint", "multibiplotGUI", "multimark", "MultiVarMI", "MuMIn", 
       "mumm", "mvord", "natural", "netCoin", "netcom", "netdiffuseR", "netgwas", 
       "netregR", "NetworkDistance", "NetworkToolbox", "neuroim", "newsmap", "nlmixr", 
       "nmathresh", "nmfgpu4R", "nmslibR", "nonlinearTseries", "nopaco", 
       "NormalBetaPrime", "NORTARA", "nowcasting", "oem", "ompr", "ompr.roi", 
       "OpenMx", "optBiomarker", "optiSel", "optismixture", "optiSolve", "optrdd", 
       "optweight", "opusminer", "ordinal", "osqp", "palasso", "panelvar", 
       "PartCensReg", "PBImisc", "pbkrtest", "PCADSC", "pcgen", "PEIP", "PenCoxFrail", 
       "perARMA", "PerFit", "permuco", "pez", "phangorn", "phia", "phylocurve", 
       "pkggraph", "PlackettLuce", "Plasmode", "PLmixed", "pmpp", "polmineR", 
       "polycor", "polywog", "powerlmm", "powerplus", "PQLseq", "predictmeans", 
       "prioritizr", "PROreg", "prozor", "PUlasso", "pulsar", "pvclass", "qgraph", 
       "qrjoint", "qrsvm", "quantable", "quanteda", "quantreg", "r2glmm", "R2MLwiN", 
       "RaceID", "ragt2ridges", "randomLCA", "ranger", "rankFD", "raptr", "rare", 
       "RCMIP5", "RcppBlaze", "RcppEigen", "Rdimtools", "Rdtq", "recipes", "refund", 
       "REndo", "repolr", "ResourceSelection", "reticulate", "RevEcoR", 
       "rFTRLProximal", "RGF", "RHPCBenchmark", "RKEEL", "Rlinsolve", "rmatio", 
       "rmgarch", "RMThreshold", "RNGforGPD", "Rnmr1D", "robustreg", "rodd", 
       "ROI.plugin.clp", "ROI.plugin.ecos", "ROI.plugin.qpoases", "ROI.plugin.scs", 
       "rolypoly", "rosqp", "Rphylopars", "rpql", "RSiena", "RSpectra", "RSSL", 
       "rstanarm", "RTransProb", "RVFam", "rWind", "rWishart", "RxODE", "saeRobust", 
       "SAVER", "sbfc", "scalpel", "scam", "SCGLR", "ScreenClean", "scrubr", "scs", 
       "SDALGCP", "SemiParSampleSel", "seqHMM", "seqMeta", "sharpr2", "SID", 
       "SimCorrMix", "simglm", "SimInf", "SimMultiCorrData", "SimRepeat", "SIRE", 
       "SISIR", "sjstats", "sklarsomega", "slimrec", "smam", "smart", "SMNCensReg", 
       "sNPLS", "spacom", "spaMM", "sparsebnUtils", "sparseFLMM", "sparseHessianFD", 
       "sparseinv", "sparseMVN", "sparsesvd", "sparsevar", "sparsio", "spatgraphs", 
       "spatstat", "spatsurv", "spGARCH", "sphet", "splm", "spmoran", "ssgraph", 
       "SSN", "STB", "stm", "stocc", "stR", "strum", "stylest", "sumFREGAT", 
       "SUMMER", "superbiclust", "surveillance", "survival", "survivalsvm", 
       "survtmle", "SwarmSVM", "synlik", "syt", "TANDEM", "tensorr", "text2vec", 
       "TFisher", "themetagenomics", "threeboost", "tidytext", "TMB", "tmle.npvi", 
       "treeDA", "trustOptim", "tsDyn", "TTCA", "tukeytrend", "tvR", "udpipe", "umx", 
       "useful", "varbvs", "varjmcm", "VCA", "vennLasso", "votesys", "wfe", "widyr", 
       "xgboost", "XGR", "xLLiM", "XMRF", "mgcv", "survival", "CaliCo", "cplm", 
       "geostatsp", "irlba", "PRIMME", "PUlasso", "Rmosek", "spGARCH", "TMB", "afex", 
       "AgreementInterval", "alphastable", "broom", "broom.mixed", "car", "CARBayes", 
       "cccd", "ccdrAlgorithm", "ChoiceModelR", "CLA", "classGraph", "cluster", 
       "corpus", "corrgram", "cpr", "DGCA", "diffusr", "dils", "dimRed", "discSurv", 
       "DoE.MIParray", "e1071", "ESEA", "extraTrees", "eyetrackingR", "flacco", 
       "FSelectorRcpp", "funrar", "gap", "gcKrig", "GDINA", "gear", "gemtc", 
       "gmodels", "h2o", "hamlet", "hdi", "HelpersMG", "HSAUR", "HSAUR2", "KFAS", 
       "lava", "lda", "lfactors", "LncPath", "loe", "matrixpls", "mefa", "mlt.docreg", 
       "NCmisc", "neat", "PAGI", "pcalg", "pergola", "prc", "PRIMME", "R.matlab", 
       "rARPACK", "rattle", "RcppArmadillo", "Rmpfr", "rmumps", "robustbase", 
       "robustvarComp", "rope", "rstan", "scidb", "sfsmisc", "sirt", "solarius", 
       "SpaDES.core", "spam", "sptm", "srvyr", "stabledist", "STPGA", "tableone", 
       "tscount", "zenplots", "cluster", "coop", "OptimalDesign", "Rcplex", "Rcsdp", 
       "Rsymphony", "rviewgraph", "skmeans", "slam")



s <- c("biogram", "BullsEyeR", "designmatch", "maptpx", "qlcMatrix", 
       "RcmdrPlugin.temis", "Rcplex", "Rglpk", "sdcTable", "bayesLopod", 
       "chinese.misc", "fPortfolio", "gofastr", "HDCI", "IMIFA", "ldatuning", 
       "lpmodeler", "LPR", "movMF", "ompr.roi", "parma", "polmineR", "rDEA", 
       "relations", "RNewsflow", "ROI", "ROI.plugin.clp", "ROI.plugin.cplex", 
       "ROI.plugin.ecos", "ROI.plugin.ipop", "ROI.plugin.msbinlp", 
       "ROI.plugin.qpoases", "ROI.plugin.quadprog", "ROI.plugin.scs", 
       "ROI.plugin.symphony", "skmeans", "stm", "textcat", "textmining", 
       "textshape", "tm", "tm.plugin.dc", "topicmodels", "Xplortext", "CVXR", 
       "DoE.MIParray", "h2o", "icarus", "quanteda", "RcppArmadillo", "rmumps", 
       "ROI.plugin.lpsolve", "ROI.plugin.neos", "sigora", "wordcloud", "coop", 
       "OptimalDesign", "Rsymphony")


barplot(b, col = "steelblue", main = "Number of Reverse Dependencies,\nImports, Suggests, etc.")
