// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// CalcLikelihoodC
double CalcLikelihoodC(arma::sp_mat dtm, NumericMatrix phi, NumericMatrix theta);
RcppExport SEXP textmineR_CalcLikelihoodC(SEXP dtmSEXP, SEXP phiSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::sp_mat >::type dtm(dtmSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type theta(thetaSEXP);
    __result = Rcpp::wrap(CalcLikelihoodC(dtm, phi, theta));
    return __result;
END_RCPP
}
// CalcSumSquares
NumericVector CalcSumSquares(arma::sp_mat dtm, NumericMatrix phi, NumericMatrix theta, NumericVector ybar);
RcppExport SEXP textmineR_CalcSumSquares(SEXP dtmSEXP, SEXP phiSEXP, SEXP thetaSEXP, SEXP ybarSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::sp_mat >::type dtm(dtmSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ybar(ybarSEXP);
    __result = Rcpp::wrap(CalcSumSquares(dtm, phi, theta, ybar));
    return __result;
END_RCPP
}
// Dtm2DocsC
List Dtm2DocsC(arma::sp_mat dtm, std::vector< std::string> vocab);
RcppExport SEXP textmineR_Dtm2DocsC(SEXP dtmSEXP, SEXP vocabSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::sp_mat >::type dtm(dtmSEXP);
    Rcpp::traits::input_parameter< std::vector< std::string> >::type vocab(vocabSEXP);
    __result = Rcpp::wrap(Dtm2DocsC(dtm, vocab));
    return __result;
END_RCPP
}
// Hellinger_cpp
double Hellinger_cpp(NumericVector p, NumericVector q);
RcppExport SEXP textmineR_Hellinger_cpp(SEXP pSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    __result = Rcpp::wrap(Hellinger_cpp(p, q));
    return __result;
END_RCPP
}
// HellingerMat
NumericMatrix HellingerMat(NumericMatrix A);
RcppExport SEXP textmineR_HellingerMat(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    __result = Rcpp::wrap(HellingerMat(A));
    return __result;
END_RCPP
}
// JSD_cpp
double JSD_cpp(NumericVector p, NumericVector q);
RcppExport SEXP textmineR_JSD_cpp(SEXP pSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    __result = Rcpp::wrap(JSD_cpp(p, q));
    return __result;
END_RCPP
}
// JSDmat
NumericMatrix JSDmat(NumericMatrix A);
RcppExport SEXP textmineR_JSDmat(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    __result = Rcpp::wrap(JSDmat(A));
    return __result;
END_RCPP
}
