# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CalcLikelihoodC <- function(dtm, phi, theta) {
    .Call(`_textmineR_CalcLikelihoodC`, dtm, phi, theta)
}

CalcSumSquares <- function(dtm, phi, theta, ybar) {
    .Call(`_textmineR_CalcSumSquares`, dtm, phi, theta, ybar)
}

Dtm2DocsC <- function(dtm, vocab) {
    .Call(`_textmineR_Dtm2DocsC`, dtm, vocab)
}

Hellinger_cpp <- function(p, q) {
    .Call(`_textmineR_Hellinger_cpp`, p, q)
}

HellingerMat <- function(A) {
    .Call(`_textmineR_HellingerMat`, A)
}

JSD_cpp <- function(p, q) {
    .Call(`_textmineR_JSD_cpp`, p, q)
}

JSDmat <- function(A) {
    .Call(`_textmineR_JSDmat`, A)
}

dtm_to_lexicon_c <- function(x) {
    .Call(`_textmineR_dtm_to_lexicon_c`, x)
}

fit_lda_c <- function(docs, Nk, Nd, Nv, alph, beta, iterations, burnin, optimize_alpha, calc_likelihood) {
    .Call(`_textmineR_fit_lda_c`, docs, Nk, Nd, Nv, alph, beta, iterations, burnin, optimize_alpha, calc_likelihood)
}

predict_lda_c <- function(docs, Nk, Nd, alpha, phi, iterations, burnin) {
    .Call(`_textmineR_predict_lda_c`, docs, Nk, Nd, alpha, phi, iterations, burnin)
}

