# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CalcLikelihoodC <- function(dtm, phi, theta) {
    .Call(`_textmineR_CalcLikelihoodC`, dtm, phi, theta)
}

CalcSumSquares <- function(dtm, phi, theta, ybar) {
    .Call(`_textmineR_CalcSumSquares`, dtm, phi, theta, ybar)
}

Dtm2DocsC <- function(dtm, vocab) {
    .Call(`_textmineR_Dtm2DocsC`, dtm, vocab)
}

HellingerMat <- function(A) {
    .Call(`_textmineR_HellingerMat`, A)
}

Hellinger_cpp <- function(p, q) {
    .Call(`_textmineR_Hellinger_cpp`, p, q)
}

JSD_cpp <- function(p, q) {
    .Call(`_textmineR_JSD_cpp`, p, q)
}

JSDmat <- function(A) {
    .Call(`_textmineR_JSDmat`, A)
}

create_lexicon <- function(Cd, Phi, dtm, alpha, freeze_topics) {
    .Call(`_textmineR_create_lexicon`, Cd, Phi, dtm, alpha, freeze_topics)
}

fit_lda_c <- function(docs, Nk, beta, alpha, Cd, Cv, Ck, Zd, Phi, iterations, burnin, freeze_topics, calc_likelihood, optimize_alpha) {
    .Call(`_textmineR_fit_lda_c`, docs, Nk, beta, alpha, Cd, Cv, Ck, Zd, Phi, iterations, burnin, freeze_topics, calc_likelihood, optimize_alpha)
}

